class Solution {
    public static boolean winnerOfGame(String colors) {
        int A = 0;
        int B = 0;
        int length = colors.length();
        for (int i = 1; i < length - 1; i++) {
            if (colors.charAt(i - 1) == 'A' && colors.charAt(i) == 'A' && colors.charAt(i + 1) == 'A') {
                A++;
            } else if (colors.charAt(i - 1) == 'B' && colors.charAt(i) == 'B' && colors.charAt(i + 1) == 'B') {
                B++;
            }
        }
        return A > B;
    }

    public static void main(String[] args) {
        boolean output = winnerOfGame(
                "AABBBBABABABAABBABBABBBBBBAABBABBABBABBBBBABAABBAABAAAAAABABBABBBAAAABAABAAABABBBBBABBBABBABBABABBBAAAABAAABBBBBAABBABBABBBBABABBBABBBABAABAABABAABBBABBBBBBBABAABAAAAAAAAAABAABBBAAABAABBBAAAABAABBBABABBABBBABABBBBBBAABBABBBABBABABBBBBAAAABBABBBAABABABBBBBBBBBBBAAABAAAABBBAABABABAABAABABAABBBBBAABBAABBAAAABAAABABBBBBBAAAABAAAAAAABBBBAABBBAABABAAABAAAABBBABBBBBBAABBBAAAABAABBBABBABBBBBAABBBBBABABBBABABBAABBBAABABBBAAAABABAAABAABBBBBBABABAAABBBBABBBABBBBBBBAABABABBBBABAABABABAABAABBBBABBBBAAABAABAABABAABABBBBAABAAAABABAABBBBABBAABBBBBBBABBAABBBBABBAABBABAABAAABBABAABBBAAABBABBBBABAAABBABABABBBBBAABABAABBBAAAABBAAAABBBBABABBBABABBABABBABBAABAAAABAAAAAAABAABAABAAAAABABAABAABAABBBABAABBAABBBABBAABAAABBBBBBAAABBABBBBBABBBBBABAAAABABAABABBBABBBAAABAABBABABABAABBBBAAABAAAAABBBBABBBAAAAAABBBBBBBAABBABBBAABAAABA");
        System.out.println(output);
    }
}